---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgA+e0mMNXQbwGdkD5jTsjlNyZAx0E7drQy6mz+pZejWpLEweQi8IYeGQF4v58GPzkuagkiKGt6C1kUcVdDtoQn/CknHrEc4uZtxU/ZNSIhxKCOQwn6Rgsr5hbD6UyLSJesgH2QgDckADfEi82/D1GStX7WGsxbN/0ApzMD7G1XqSh2SLqrpH+WzLLP+f4hdXmM6Yy1SqbdS2R3DNdgTRD9bCWIGQHbvkIVDZiOqnKoZnSVxrd/VksHMZ5qMsfVskxTjRC1VoIR9Qrxe6KNQn/XSlut1UGZyiLLQejdWLEcDk3NwP4qS50GPBzj8Wocm4dNi32Dd6UqqXSneNEGmjHyE/P4AbokmkGJqjhAZfVocjLrRSFh1ZXAeeSJNqNomGNTSZerhA4A/Qq7rnkxdJ3H/Y5zd+Pa2yz0GCnbkmN+f4Uvx2hM45eB2dYtpkERw8GBDKGITrg5JlNVEhPjX5aCvGd/2OQoX7k81X2t1/R3gwAwzGibYKPaoXnc9MJ0Zw7nb3bSePOWsaWlteLvDsUsYGYFGcYJwOxyXCkVUAP5noQ586GxytTJzIV+j2uNLWdt3nUO5CDHDluiavFn2RThzCI5+h0DVzRl6pDkqcgDUbOQpQpYBjkIrmyygSbrmE3XZSy3HaSSAiynMPT5BypD1AMIMwD2UYW3Ayftebc8cZEctlL87REFGPGcGT0B9XIxdpfzUtEM47LM9GCKVGjFfqtshHlqDqlSmldJo9FEAhQ0DAmxV3rNcHE3Mj5dycNHy0dDsrGfkqD85psKSkBz5G7FWrg==
  template:
    metadata:
      name: backend-secrets
      namespace: default
