apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgCHKF+/S7cGyckn5AWOpkvlHEAfa0HUu643r5nS8S4hD5cf+vdvM4gEvVXj/Ew7Dv7WkY35wMw0KCUbifVjcLfItI/Rmy7mmUUXI7hEAxjoNJIeTac7ccaAd2tMOhqk4AwWJhSfePRV53qhbY/DPmG1+6rR022NVHDS6XxePW3QkupLGjpXYfXJcaXZFS/EgGJWMo86mgl28Qk7edsKAC//15l3OsJWAvCr0454JRGBh+zt0c9kiMn9ioikYMOWi7H7oCYQA5RlEMToGKov0+jq6D/YL/5D3Hca+MVMp2oMBzGFBUjBr75rFWRnAnQBHHhhq3n8wpkH6hSdgkhSm33sUsQXJdheiyKKYD9Kyeo4Nh3IOndhUNMhAcDeLILfx7Bokgjcxe76MqmMsAlVTiiqlULTJeV+gFQyPfAD8f16YiboO5vH+Mknl56aDeQvZKI0ViSUtzc1z+eRmWb0GwIwjYl9jaIcwyTAFeEfoaqCeL5ZT0v8e2MuNM45fT+adwlDjs9qlY7P7bB6jce3H0Bp/tK+83Qi+l5eyiO9zfBfaT6xhEsZs4qqARpi5lwwrU163MzNPp4ITdOTqG4BP1YUI23ZmlS8jNieW0j3IlLzSvRb42fCZer2luBFQ1VyITzDSi72QWHFyfR20Trtc2cBjpVB8fKzEX5mTGSzBt7MvqklU6YnyhzrndXbE1tLAPV8KLep9GD3E3ULd5KLCBpdsm9mLhdAcDJFq4cSaMpycimxZQpbvzQTXaM3j5Ew+Vuci5hN5Pk7EQFId2hRrl/0NtnOrg==
  template:
    metadata:
      name: backend-secrets
      namespace: default
