apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgAdTUTJ5fOvyACYI3oiL9Opirb4F5kEp+svLtrtZYxsK6FM84ngQfwNuynrDzkp9jTEvgmZfGJo2qvRrHZebCTxNbxbRn460mXYQq2A0J+N+U9XJns3N9+Ff9rNIaoUOs7p1GYrjgtQZwlambPOO/xE/KdvOAGkKwJNydUPoOGReZv2ideABNWLM5iOm6jevNLHSuLj3K9BV8SHlSFehu1Cr8/o07dsgnT+TsPhlUDA4IlwuG72T2o6dYj2VSOsGdb3WV2dRpjkkq/Bx+yS64SPvd98ClyCZdSt7AYBNa9Eu48xy9GIsWx5acTvTpndBLCxevFcr5Zsz2dmPP4F+tvayvz13/wvPNwBoyqXMUR1+4+Yt8gCkOJVfVH76uYA1RtTIemy9C1cCZpPkrJS/qE4EIxrCvWjdgo/bczrfCvQJdeOnGGL/ynSS8iApi26P5J2V5hJONifXW0Ok2uB240DbLyv1wR//7tWNRqudsjFLWOf30X0DylobZPXdpULmbcHy6Sz9RnXQI1ezCBFTisa5m0ReeYRJLr64MZP6ruwiobLm8gOJiehjP3Czy/pv4DfdMaJwxqiGeqOJTua9IWMv1LN4/vuvxGU56XsAWBwfUL+GCkYtHi7vG8EuzTQN1qMPUpe9WLNb/wX0ErPD9iNRCPoAvTRPZejEgLSr29WX5hy+KAtCjwvXxAmDPsfsZ0GoIp32gT3I1wTuJDAIGIRsDktQGiPapXpt4A1x/RAgog4yoGf8Ihk1jROydDj2o12PxgioGMC1Le5m/6FXw06uFMwrQ==
  template:
    metadata:
      name: backend-secrets
      namespace: default
