---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-secrets
  namespace: default
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgCh5aTx+UODPWyfAuPvAawtDFO5AABoBPEWW/vzY69x58WBuX/ry8RzC0Tl9jMZ/9pdrPrbLzgIj93fSddZX7nfMUVPy5qx/JczdCjqw9NiSxbv0xw/jDPbnpQwHHqel2PurhW83c7JS9o9lFyCX79GRZGOniLvP5eKanraxUonjaVL/97sol1ZXhUsjBr8W21Xvf4yZZu1b93tnw575qWxeDuVyClbNdMUphqeZLScVyvFf7RzmRrfJ1rjtyEE16aWiWPp0nIDvuC11DE/AplDNgtyBBtdGMjopUfyezSA0gZccwmoA+TM9d5uXWzt5z3Wgwz2aYxGmOt0YvOEPFSrZTi+SHakX+HSpMQxFaX00Rw8TU0HDMIgQ6edRQThKZKJsK4OhlfZaO3hYBS/Ttn6rjWp6Uh7elFcgtBvmJEfV+c/HvszMN6tR+HNbmOwEyigZH4xxnXC2M42XvyaWKNbuBHFCKYFlNdE8r33RxUaAFhXw30KC1aVni38wAwLF2QZ7kjJd6UpFykt+zy7EvTQYPOLFW0rtCftTSU9Zd9e+iMrUxDz4wWFoPtLwKhgGxkonGXnN42Psa0UCBrw3NyA0CXwlA/JxaEdmobQeOeuY7DdRhDTlnnY9/NWbfTqq7vUnv3VmpfqMfyMgbj1Hfyd6bUPgV8f3kUgvP/CoymjYyhVa6dvOaWQjz6kwRBq9y+/E8kRTgliPvDy
    MONGO_INITDB_ROOT_USERNAME: AgB0Vlm/LOrHm0FZGLhlWC0DVlyvnOlM33Zl6JRVdZtBoBcDmS6iwYF1cR+MdyLae6TdldY+bHntV/M0QCLkSSOUBanQwzi31PZ6B5P5gWFbpfZjqinmmIjjgYiJBw6JvvN9HEg5Vs4wvGU+4Cm7eJhR8jOtUEaPsniwlLBYDRLi8Dk3P+KnWCBPrKMGjCg/3x3v+m32mFbbaOAcpwwVEzYNqDlxh/uKEMZNMg2mqXwP9vnnZ8GZlLV3I85uOW+hpQXPCgeKeCFdX+0gLQrov4UDBTlwpyzK9/ejdfwLVAIisH+sWBjR4U5cOTDagUp2eTavBqqo8d8rOLx4hhdA0xHi0JEy/laeBXbeLz3TaydIrk0H+O6SCJnt7Hxkd4MMe3Q/r1fyLVyiaA3+0xD+FMS+eKFzJLZSdROo9AneKSjljm3DSrf1hqGmhqNaNPZnbGf4jBysH8acprB0TaTa25vwO3PjULTAMTiuJnUFkz9/ruCPWOCHy48OmYBB18J/bCv8UEj4+XYsdamuMKcIvD9CZHwrx1OvO+B731uRJFXP4kIQEI+RumbSv661CrKRhagNrIx9Cu3VyozjkFHYZVU7utyWnxOa81H6E7GRmfIf66xvOOCu7N6nl7BTe2mBN3P3OWFgPje9E7Ed73VTGBZSy1XTmgRGuRli63WFgVUPYp19A3g+HNH3jjsfy0vwG6Lv3hg2Cw==
  template:
    metadata:
      name: mongo-secrets
      namespace: default
